name: Auto Update Live Playlist

on:
  workflow_dispatch:   # ⬅️ INI PENTING (manual run)
  schedule:
    - cron: "0 */3 * * *"
  push:
    paths:
      - "playlist/**"
      - "epg.xml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Generate playlist
        run: python playlist/playlist_generator.py

      - name: Commit live.m3u
        run: |
          git config user.name "actions-user"
          git config user.email "actions@github.com"
          git add live.m3u
          git commit -m "Auto update live.m3u" || echo "No changes"
          git push
